version: "2"

prepare:
  fetch:
    - url: https://raw.githubusercontent.com/g5search/g5-rubocop-style/v1.0.1/default.yml
      path: .rubocop-https---raw-githubusercontent-com-g5search-g5-rubocop-style-v1-0-1-default-yml

plugins:
  rubocop:
    enabled: true
    channel: "rubocop-0-90"
